const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  readdir: (path) => ipcRenderer.invoke('fs:readdir', path),
  stat: (path) => ipcRenderer.invoke('fs:stat', path),
  readFile: (path, encoding) => ipcRenderer.invoke('fs:readFile', path, encoding),
  writeFile: (path, content) => ipcRenderer.invoke('fs:writeFile', path, content),
  mkdir: (path) => ipcRenderer.invoke('fs:mkdir', path),
  rename: (oldPath, newPath) => ipcRenderer.invoke('fs:rename', oldPath, newPath),
  copy: (src, dest) => ipcRenderer.invoke('fs:copy', src, dest),
  move: (src, dest) => ipcRenderer.invoke('fs:move', src, dest),
  delete: (path) => ipcRenderer.invoke('fs:delete', path),
  batchRename: (renames) => ipcRenderer.invoke('fs:batchRename', renames),
  chmod: (path, mode) => ipcRenderer.invoke('fs:chmod', path, mode),
  getHomeDir: () => ipcRenderer.invoke('fs:getHomeDir'),
  getDrives: () => ipcRenderer.invoke('fs:getDrives'),
  search: (params) => ipcRenderer.invoke('fs:search', params),
  zip: (params) => ipcRenderer.invoke('fs:zip', params),
  unzip: (params) => ipcRenderer.invoke('fs:unzip', params),
  findDuplicates: (dir) => ipcRenderer.invoke('fs:findDuplicates', dir),
  moveDuplicates: (params) => ipcRenderer.invoke('fs:moveDuplicates', params),
  folderSize: (dir) => ipcRenderer.invoke('fs:folderSize', dir),
  addTag: (params) => ipcRenderer.invoke('tags:add', params),
  removeTag: (params) => ipcRenderer.invoke('tags:remove', params),
  getTags: (path) => ipcRenderer.invoke('tags:get', path),
  getAllTags: () => ipcRenderer.invoke('tags:getAll'),
  searchByTag: (tagName) => ipcRenderer.invoke('tags:searchByTag', tagName),
  getLog: (params) => ipcRenderer.invoke('log:getAll', params),
  clearLog: () => ipcRenderer.invoke('log:clear'),
  undo: () => ipcRenderer.invoke('undo:perform'),
  getRules: () => ipcRenderer.invoke('rules:getAll'),
  saveRule: (rule) => ipcRenderer.invoke('rules:save', rule),
  deleteRule: (id) => ipcRenderer.invoke('rules:delete', id),
  runRule: (id) => ipcRenderer.invoke('rules:run', id),
  storeGet: (key) => ipcRenderer.invoke('store:get', key),
  storeSet: (key, value) => ipcRenderer.invoke('store:set', key, value),
  getBookmarks: () => ipcRenderer.invoke('bookmarks:get'),
  saveBookmarks: (bookmarks) => ipcRenderer.invoke('bookmarks:save', bookmarks),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  openPath: (path) => ipcRenderer.invoke('shell:openPath', path),
  showInFinder: (path) => ipcRenderer.invoke('shell:showItemInFinder', path),
  showOpenDialog: (opts) => ipcRenderer.invoke('dialog:showOpenDialog', opts),
  showSaveDialog: (opts) => ipcRenderer.invoke('dialog:showSaveDialog', opts),
  ptyCreate: (params) => ipcRenderer.invoke('pty:create', params),
  ptyWrite: (data) => ipcRenderer.invoke('pty:write', data),
  ptyResize: (params) => ipcRenderer.invoke('pty:resize', params),
  ptyCd: (dir) => ipcRenderer.invoke('pty:cd', dir),
  ptyDestroy: () => ipcRenderer.invoke('pty:destroy'),
  onPtyData: (cb) => ipcRenderer.on('pty:data', (_, data) => cb(data)),
  offPtyData: () => ipcRenderer.removeAllListeners('pty:data'),
  watcherStart: (path) => ipcRenderer.invoke('watcher:start', path),
  watcherStop: (path) => ipcRenderer.invoke('watcher:stop', path),
  onWatcherChange: (cb) => ipcRenderer.on('watcher:change', (_, data) => cb(data)),
  offWatcherChange: () => ipcRenderer.removeAllListeners('watcher:change'),
});